// ==UserScript==
// @name         Hack Forums Old Smileys
// @author       ameyarora
// @namespace    https://github.com/ameyarora/hf_scripts
// @version      1.0
// @description  Adds old gif smileys to sceditor
// @require      https://code.jquery.com/jquery-3.1.1.js
// @match        *hackforums.net/newreply.php?tid=*
// @match        *hackforums.net/newthread.php?fid=*
// @match        *hackforums.net/editpost.php?pid=*
// @match        *hackforums.net/private.php?action=send*
// @copyright    2020+
// @updateURL    https://github.com/ameyarora/hf_scripts//raw/master/OldSmileys.user.js
// @downloadURL  https://github.com/ameyarora/hf_scripts//raw/master/OldSmileys.user.js
// @iconURL      https://raw.githubusercontent.com/ameyarora/hf_scripts/master/icon.png
// ------------------------------ Change Log ----------------------------
// version 1.0: Release
// ==/UserScript==
// ------------------------------ On Page ------------------------------

// Thread Reply, Edit & New Thread
if (window.location.href.includes("hackforums.net/newreply.php?tid=")||
         window.location.href.includes("hackforums.net/newthread.php?fid=")||
         window.location.href.includes("hackforums.net/editpost.php?pid=")){
    $("div:contains(Bold)").eq(3).prepend($("<tr>")
                                                           .append($("<td>").addClass("trow1")
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/pinch.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/pinch.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/victoire.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/victoire.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/hehe.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/hehe.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 10px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/oui.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/oui.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/blink.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/blink.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 10px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/biggrin.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/biggrin.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/sad.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/sad.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/unsure.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/unsure.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/glare.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/glare.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 10px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/roflmao.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/roflmao.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/devlish.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/devlish.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 10px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/rolleyes.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/rolleyes.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/cool.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/cool.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 8px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/gratte.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/gratte.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/confused.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/confused.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 10px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/ninja.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/ninja.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/blush.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/blush.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 10px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/lipssealed.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/lipssealed.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/non.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/non.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 10px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/smile.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/smile.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/sleep.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/sleep.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 10px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/evilgrin.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/evilgrin.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/omg.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/omg.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 0px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/tongue.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/tongue.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/mad.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/mad.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 10px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/huh.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/huh.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/wacko.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/wacko.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 10px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/ohmy.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/ohmy.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/pirate.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/pirate.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/nono.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/nono.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/bebe-pleure.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/bebe-pleure.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/superman.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/superman.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/blackhat.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/blackhat.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/yeye.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/yeye.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/whistle.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/whistle.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/thumbsup.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/thumbsup.gif'>"))
                                                                  ));
}

//Private Message Full Reply
else if (window.location.href.includes("hackforums.net/private.php?action=send")) {
        $("div:contains(Bold)").eq(5).prepend($("<tr>")
                                                           .append($("<td>").addClass("trow1")
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/pinch.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/pinch.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/victoire.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/victoire.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/hehe.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/hehe.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 10px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/oui.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/oui.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/blink.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/blink.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 10px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/biggrin.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/biggrin.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/sad.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/sad.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/unsure.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/unsure.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/glare.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/glare.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 10px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/roflmao.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/roflmao.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/devlish.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/devlish.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 10px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/rolleyes.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/rolleyes.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/cool.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/cool.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 8px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/gratte.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/gratte.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/confused.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/confused.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 10px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/ninja.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/ninja.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/blush.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/blush.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 10px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/lipssealed.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/lipssealed.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/non.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/non.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 10px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/smile.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/smile.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/sleep.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/sleep.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 10px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/evilgrin.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/evilgrin.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/omg.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/omg.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 0px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/tongue.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/tongue.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/mad.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/mad.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 10px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/huh.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/huh.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/wacko.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/wacko.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 10px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/ohmy.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/ohmy.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/pirate.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/pirate.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/nono.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/nono.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/bebe-pleure.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/bebe-pleure.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/superman.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/superman.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/blackhat.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/blackhat.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/yeye.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/yeye.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/whistle.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/whistle.gif'>"))
                                                                   .append($("<span>").addClass("oldsmileys").attr("style","margin: 5px; font-size: 18px; flex: 1 0 calc(25% - 10px); cursor: pointer;").attr("onclick","MyBBEditor.insertText('[img]https://hackforums.net/images/smilies/thumbsup.gif[/img]');").html("<img src='https://hackforums.net/images/smilies/thumbsup.gif'>"))
                                                                  ));
};